INF-2227: Add documentation for COManage CO Group provisioning.
osg-htc/technology pull request #144
Opened 2024-08-16 20:37 UTC by williamnswanson

2024-08-21 14:48 UTC, mwestphall approved these changes
I was able to follow this document to add a new COManage Group, looks good.

2024-08-21 15:02 UTC, brianhlin requested changes
I've got thoughts on formatting but will have to provide details at a later time

2024-10-11 19:50 UTC, brianhlin reviewed
See in-line comments. Mostly nit-picky stuff to adhere to our style guide: https://osg-htc.org/technology/documentation/style-guide/.  Make sure to batch commits together when accepting suggestions (https://osg-htc.org/technology/software/git-software-development/#batch-commits-when-accepting-suggestions-from-a-review)

Also as a heads up, you should basically never submit PRs from your main / master branches as the default PR behavior is to allow the maintainer to add commits to your PR, i.e. your fork's main / master branch

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> +This section contains some common actions administrators perform on the OSG COManage, and how to do so.
```suggestion
```

All of this basically just repeats what you say in the sentence above. Also, adding a section level here adds noise to the section hierarchy and it's not entirely clear why we need it (if we have another section in this doc at the same level, what would it actually be?)

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> +1. #### Create CO Group in COManage and add members (or use existing CO Group)
```suggestion
### Create CO Group in COManage and add members (or use existing CO Group)
```

I don't think we need to make something a section header AND an enumerated step

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> +    -   Navigate to the `All Groups` page in COManage and click the `+ Add Group` button near the top-right.
```suggestion
    1.  **If using an already existing group, skip to the next step.** Navigate to the `All Groups` page in COManage and click the `+ Add Group` button near the top-right.
```

Combining and bolding here helps with clarity. Also, this section has two steps that should happen in order (if doing both). We use bulleted lists more when we're describing exclusive options, or an unordered list

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> +        As the creator of the Group, you will already have both Membership in, and Ownership over, the new group.
```suggestion
        As the creator of the Group, you will already have both Membership in and Ownership over the new group.
        Remove yourself as appropriate.
```

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> +In order for a CO Group from COManage to show up in LDAP (and thus be made available for reference on Hosts),
```suggestion

In order for a CO Group from COManage to show up in LDAP (and thus be made available for reference on hosts),
```

Adding a linebreak between the heading and content for readability, not sure why hosts was capitalized

2024-10-11 19:50 UTC, brianhlin commented on docs/operations/comanage-recipes.md
> + it must first be provisioned.
I think it'd be worth adding an admonition here to speak to the fact that OIDC clients needing groups don't need any of these steps outside of the group creation (see https://osg-htc.org/technology/documentation/style-guide/#notes and https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types)

```
```

2024-12-13 20:04 UTC, williamnswanson commented on docs/operations/comanage-recipes.md
> +        As the creator of the Group, you will already have both Membership in, and Ownership over, the new group.
```suggestion
        As the creator of the group you will already have both Membership in, and Ownership over, the new group.
        
        Remove yourself as appropriate.
```
Github won't let me add two suggestions for the same line, so I'm just making one suggestion with both fixes (capitalization and only having one type of comma in a sentance).

2024-12-13 21:38 UTC, closed without merging